#!/bin/bash
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
        deb-systemd-invoke stop joycond.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/systemd-demo" ] || [ -e "/etc/init/systemd-demo.conf" ]; then
        invoke-rc.d systemd-demo stop || exit $?
fi
# End automatically added section