#!/bin/bash

if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" ] || ( [ abort-upgrade = "$1" ] && dpkg --compare-versions "$2" lt 1.0-1+24.04 ); then
    dpkg-divert --package switch-alsa-ucm2 --remove --rename \
        --divert /usr/share/alsa/ucm2/Tegra/tegra-hda/tegra-hda-HiFi.conf.orig /usr/share/alsa/ucm2/Tegra/tegra-hda/tegra-hda-HiFi.conf
    dpkg-divert --package switch-alsa-ucm2 --remove --rename \
        --divert /usr/share/wireplumber/main.lua.d/50-alsa-config.lua.orig /usr/share/wireplumber/main.lua.d/50-alsa-config.lua
fi
