#!/bin/bash

if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" ]; then
    dpkg-divert --package switch-alsa-ucm2 --remove --rename \
        --divert /usr/share/alsa/ucm2/Tegra/tegra-hda/tegra-hda-HiFi.conf.orig /usr/share/alsa/ucm2/Tegra/tegra-hda/tegra-hda-HiFi.conf
fi
