#!/bin/bash

if [ upgrade != "$1" ] || dpkg --compare-versions "$2" lt 1.0-5; then
    dpkg-divert --package nvidia-bsp-32-3 --add --rename --divert /usr/lib/aarch64-linux-gnu/tegra/libdrm.orig /usr/lib/aarch64-linux-gnu/tegra/libdrm.so.2
    dpkg-divert --package nvidia-bsp-32-3 --add --rename --divert /usr/lib/aarch64-linux-gnu/libdrm_nvdc.orig /usr/lib/aarch64-linux-gnu/libdrm_nvdc.so
    ldconfig
fi
