#!/bin/bash

divert() {
    dpkg-divert --package switch-dock-handler --add --rename --divert "${1}.orig" "$1"
}

if [ upgrade != "$1" ] || dpkg --compare-versions "$2" lt 2.2-1; then
    divert /etc/udev/rules.d/90-alsa-asound-tegra.rules
    divert /etc/udev/rules.d/92-hdmi-audio-tegra.rules
    rm -f /etc/asound.conf || true
fi
