#!/bin/bash

# cleanup kscreen cache to avoid potential issues after upgrade, such as wrong display configuration.
if [ upgrade != "$1" ] || dpkg --compare-versions "$2" lt 1.0-9; then
  rm -rf /home/*/.config/monitors.xml /home/*/.config/unity-monitors.xml
fi

true
